apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sneek-peak-back
spec:
  rules:
    - host: sneek-peak-back.orchestrate.ops.consensys.net
      http:
        paths:
          - backend:
              serviceName: sneak-peek-back
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - sneek-peak-back.orchestrate.ops.consensys.net
