apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sneak-peek-front
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: sneak-peek.ops.consensys.net
      http:
        paths:
          - backend:
              serviceName: sneak-peek-front
              servicePort: 80
            path: /.*
  tls:
    - hosts:
        - sneak-peek.ops.consensys.net
